# Generated by Django 3.2.6 on 2021-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20210818_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='albums.Genre'),
        ),
    ]
