# Generated by Django 3.2.6 on 2021-08-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='genres',
        ),
    ]
