# Generated by Django 3.2.4 on 2021-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='albums.Genre'),
        ),
    ]
