# Generated by Django 3.2.4 on 2021-06-24 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_album_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
