# Generated by Django 3.2.4 on 2021-08-17 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
